### ISSUE TITLE
Unable to run _genonce.sh on vrdr-testbed

### ISSUE THREAD

**Issue by johnarleyburns** [nightingaleproject/vrdr-testbed#3]
Able to run sushi, but _genonce.sh fails with the error below.  The pre-nightingale-migration version of vrdr-testbed worked fine with _genonce.sh.  Running "npm install -g fsh-sushi" has no effect:

Sushi: ========================= SUSHI RESULTS ===========================       (00:04.502)
Sushi: |  -------------------------------------------------------------  |       (00:04.502)
Sushi: | |    Profiles   |  Extensions  |   Logicals   |   Resources   | |       (00:04.502)
Sushi: | |-------------------------------------------------------------| |       (00:04.502)
Sushi: | |       0       |      0       |      0       |       0       | |       (00:04.502)
Sushi: |  -------------------------------------------------------------  |       (00:04.502)
Sushi: |  -------------------------------------------------------------  |       (00:04.503)
Sushi: | |      ValueSets     |    CodeSystems    |     Instances      | |       (00:04.503)
Sushi: | |-------------------------------------------------------------| |       (00:04.503)
Sushi: | |         0          |         0         |         39         | |       (00:04.503)
Sushi: |  -------------------------------------------------------------  |       (00:04.503)
Sushi: |                                                                 |       (00:04.503)
Sushi: ===================================================================       (00:04.504)
Sushi: | Don't be koi about asking for help     3 Errors     25 Warnings |       (00:04.504)
Sushi: ===================================================================       (00:04.504)
Sushi:                                                                           (00:04.504)
Sushi couldn't be run. Complete output from running Sushi :                      (00:04.507)
Note: Check that Sushi is installed correctly ("npm install -g fsh-sushi". On windows, get npm from https://www.npmjs.com/get-npm) (00:04.507)
Exception: Process exited with an error: 3 (Exit value: 3)                       (00:04.507)
Publishing Content Failed: Process exited with an error: 3 (Exit value: 3)       (00:04.508)
                                                                                 (00:04.508)
Use -? to get command line help                                                  (00:04.508)
                                                                                 (00:04.508)
Stack Dump (for debugging):                                                      (00:04.509)
org.apache.commons.exec.ExecuteException: Process exited with an error: 3 (Exit value: 3)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
        at org.hl7.fhir.igtools.publisher.FSHRunner.runFsh(FSHRunner.java:83)
        at org.hl7.fhir.igtools.publisher.Publisher.initialize(Publisher.java:2249)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:906)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:10973)

**Comment by johnarleyburns** [comment]
Misunderstanding; only with zero sushi errors can you run IG Publisher.
